name: "medchain-network"

# Describe what the target network is/does.
description: "The network which will host the MedChain blockchain"

# Schema version of the content. Used by the SDK to apply the corresponding parsing rules.
version: 2

# The client section used by GO SDK.
client:
  # Which organization does this application instance belong to? The value must be the name of an org
  organization: Providers
  logging:
    level: DEBUG #info CRITICAL | ERROR | WARNING | NOTICE | INFO | DEBUG

  # Global configuration for peer, event service and orderer timeouts
  peer:
    timeout:
      connection: 3s
      queryResponse: 45s
      executeTxResponse: 30s
  eventService:
    timeout:
      connection: 3s
      registrationResponse: 3s
  orderer:
    timeout:
      connection: 3s
      response: 5s

  # Root of the MSP directories with keys and certs. The Membership Service Providers is component that aims to offer an abstraction of a membership operation architecture.
  cryptoconfig:
    path: "${GOPATH}/src/medchain/medchain-network/fixtures/crypto-config"

  # Some SDKs support pluggable KV stores, the properties under "credentialStore" are implementation specific
  credentialStore:
    path: "/tmp/medchain-network-kvs"

     # [Optional]. Specific to the CryptoSuite implementation used by GO SDK. Software-based implementations requiring a key store. PKCS#11 based implementations does not.
    cryptoStore:
      path: "/tmp/medchain-network-msp"

  # BCCSP config for the client. Used by GO SDK. It's the Blockchain Cryptographic Service Provider.
  # It offers the implementation of cryptographic standards and algorithms.
  BCCSP:
    security:
     enabled: true
     default:
      provider: "SW"
     hashAlgorithm: "SHA2"
     softVerify: true
     ephemeral: false
     level: 256

  tlsCerts:
    systemCertPool: false

# [Optional]. But most apps would have this section so that channel objects can be constructed based on the content below.
# If one of your application is creating channels, you might not use this
channels:
  medchain:
    orderers:
      - orderer.hf.medchain.global

    # Network entity which maintains a ledger and runs chaincode containers in order to perform operations to the ledger. Peers are owned and maintained by members.
    peers:
      peer0.providers.hf.medchain.global:
        # [Optional]. will this peer be sent transaction proposals for endorsement? The peer must
        # have the chaincode installed. The app can also use this property to decide which peers
        # to send the chaincode install request. Default: true
        endorsingPeer: true

        # [Optional]. will this peer be sent query proposals? The peer must have the chaincode
        # installed. The app can also use this property to decide which peers to send the
        # chaincode install request. Default: true
        chaincodeQuery: true

        # [Optional]. will this peer be sent query proposals that do not require chaincodes, like
        # queryBlock(), queryTransaction(), etc. Default: true
        ledgerQuery: true

        # [Optional]. will this peer be the target of the SDK's listener registration? All peers can
        # produce events but the app typically only needs to connect to one to listen to events.
        # Default: true
        eventSource: true

      peer1.providers.hf.medchain.global:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: false

      peer0.storages.hf.medchain.global:
        endorsingPeer: false
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

      peer1.storages.hf.medchain.global:
        endorsingPeer: false
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: false

      peer0.patients.hf.medchain.global:
        endorsingPeer: false
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: false
      peer1.patients.hf.medchain.global:
        endorsingPeer: false
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: false

      peer0.researchers.hf.medchain.global:
        endorsingPeer: false
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: false
      peer1.researchers.hf.medchain.global:
        endorsingPeer: false
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: false

  emr:
    orderers:
        - orderer.hf.medchain.global
    peers:
      peer0.providers.hf.medchain.global:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

      peer1.providers.hf.medchain.global:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: false

      peer0.storages.hf.medchain.global:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

      peer1.storages.hf.medchain.global:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: false

  amr:
    orderers:
          - orderer.hf.medchain.global
    peers:
      peer0.providers.hf.medchain.global:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

      peer1.providers.hf.medchain.global:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: false

      peer0.researchers.hf.medchain.global:
          endorsingPeer: true
          chaincodeQuery: true
          ledgerQuery: true
          eventSource: false
      peer1.researchers.hf.medchain.global:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: false
  pii:
    orderers:
          - orderer.hf.medchain.global
    peers:
      peer0.providers.hf.medchain.global:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

      peer1.providers.hf.medchain.global:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: false

      peer0.patients.hf.medchain.global:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: false
      peer1.patients.hf.medchain.global:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: false
  directory:
      orderers:
            - orderer.hf.medchain.global
      peers:
        peer0.providers.hf.medchain.global:
          endorsingPeer: true
          chaincodeQuery: true
          ledgerQuery: true
          eventSource: true

        peer1.providers.hf.medchain.global:
          endorsingPeer: true
          chaincodeQuery: true
          ledgerQuery: true
          eventSource: false

        peer0.patients.hf.medchain.global:
          endorsingPeer: true
          chaincodeQuery: true
          ledgerQuery: true
          eventSource: false
        peer1.patients.hf.medchain.global:
          endorsingPeer: true
          chaincodeQuery: true
          ledgerQuery: true
          eventSource: false



# List of participating organizations in this network
organizations:
  Providers:
    mspid: providers.hf.medchain.global
    cryptoPath: "peerOrganizations/providers.hf.medchain.global/users/{userName}@providers.hf.medchain.global/msp"
    peers:
      - peer0.providers.hf.medchain.global
      - peer1.providers.hf.medchain.global
    certificateAuthorities:
      - ca.providers.hf.medchain.global
  Storages:
    mspid: storages.hf.medchain.global
    cryptoPath: "peerOrganizations/storages.hf.medchain.global/users/{userName}@storages.hf.medchain.global/msp"
    peers:
      - peer0.storages.hf.medchain.global
      - peer1.storages.hf.medchain.global
    certificateAuthorities:
      - ca.storages.hf.medchain.global

  Patients:
    mspid: patients.hf.medchain.global
    cryptoPath: "peerOrganizations/patients.hf.medchain.global/users/{userName}@patients.hf.medchain.global/msp"
    peers:
      - peer0.patients.hf.medchain.global
      - peer1.patients.hf.medchain.global
    certificateAuthorities:
      - ca.storages.hf.medchain.global

  Researchers:
    mspid: researchers.hf.medchain.global
    cryptoPath: "peerOrganizations/researchers.hf.medchain.global/users/{userName}@researchers.hf.medchain.global/msp"
    peers:
      - peer0.researchers.hf.medchain.global
      - peer1.researchers.hf.medchain.global
    certificateAuthorities:
      - ca.storages.hf.medchain.global

# List of orderers to send transaction and channel create/update requests to.
# The orderers consent on the order of transactions in a block to be committed to the ledger. For the time being only one orderer is needed.
orderers:
  orderer.hf.medchain.global:
    url: grpcs://localhost:7050
    grpcOptions:
      ssl-target-name-override: orderer.hf.medchain.global
      grpc-max-send-message-length: 15
    tlsCACerts:
      path: "${GOPATH}/src/medchain/medchain-network/fixtures/crypto-config/ordererOrganizations/hf.medchain.global/tlsca/tlsca.hf.medchain.global-cert.pem"

# List of peers to send various requests to, including endorsement, query and event listener registration.
peers:
  peer0.providers.hf.medchain.global:
    # this URL is used to send endorsement and query requests
    url: grpcs://localhost:7051
    # this URL is used to connect the EventHub and registering event listeners
    eventUrl: grpcs://localhost:7053
    # These parameters should be set in coordination with the keepalive policy on the server
    grpcOptions:
      ssl-target-name-override: peer0.providers.hf.medchain.global
      grpc.http2.keepalive_time: 15

    tlsCACerts:
      path: "${GOPATH}/src/medchain/medchain-network/fixtures/crypto-config/peerOrganizations/providers.hf.medchain.global/tlsca/tlsca.providers.hf.medchain.global-cert.pem"

  peer1.providers.hf.medchain.global:
    url: grpcs://localhost:8051
    eventUrl: grpcs://localhost:8053
    grpcOptions:
      ssl-target-name-override: peer1.providers.hf.medchain.global
      grpc.http2.keepalive_time: 15
    tlsCACerts:
      # Certificate location absolute path
      path: "${GOPATH}/src/medchain/medchain-network/fixtures/crypto-config/peerOrganizations/providers.hf.medchain.global/tlsca/tlsca.providers.hf.medchain.global-cert.pem"


  peer0.storages.hf.medchain.global:
    url: grpcs://localhost:9051
    eventUrl: grpcs://localhost:9053
    grpcOptions:
      ssl-target-name-override: peer0.storages.hf.medchain.global
      grpc.http2.keepalive_time: 15

    tlsCACerts:
      path: "${GOPATH}/src/medchain/medchain-network/fixtures/crypto-config/peerOrganizations/storages.hf.medchain.global/tlsca/tlsca.storages.hf.medchain.global-cert.pem"

  peer1.storages.hf.medchain.global:
    url: grpcs://localhost:8061
    eventUrl: grpcs://localhost:8063
    grpcOptions:
      ssl-target-name-override: peer1.storages.hf.medchain.global
      grpc.http2.keepalive_time: 15
    tlsCACerts:
      path: "${GOPATH}/src/medchain/medchain-network/fixtures/crypto-config/peerOrganizations/storages.hf.medchain.global/tlsca/tlsca.storages.hf.medchain.global-cert.pem"

  peer0.patients.hf.medchain.global:
    url: grpcs://localhost:10051
    eventUrl: grpcs://localhost:10053
    grpcOptions:
      ssl-target-name-override: peer0.patients.hf.medchain.global
      grpc.http2.keepalive_time: 15
    tlsCACerts:
      path: "${GOPATH}/src/medchain/medchain-network/fixtures/crypto-config/peerOrganizations/patients.hf.medchain.global/tlsca/tlsca.patients.hf.medchain.global-cert.pem"

  peer1.patients.hf.medchain.global:
    url: grpcs://localhost:10061
    eventUrl: grpcs://localhost:10063
    grpcOptions:
      ssl-target-name-override: peer1.patients.hf.medchain.global
      grpc.http2.keepalive_time: 15
    tlsCACerts:
      path: "${GOPATH}/src/medchain/medchain-network/fixtures/crypto-config/peerOrganizations/patients.hf.medchain.global/tlsca/tlsca.patients.hf.medchain.global-cert.pem"

  peer0.researchers.hf.medchain.global:
    url: grpcs://localhost:11051
    eventUrl: grpcs://localhost:11053
    grpcOptions:
      ssl-target-name-override: peer1.researchers.hf.medchain.global
      grpc.http2.keepalive_time: 15
    tlsCACerts:
      path: "${GOPATH}/src/medchain/medchain-network/fixtures/crypto-config/peerOrganizations/researchers.hf.medchain.global/tlsca/tlsca.researchers.hf.medchain.global-cert.pem"
  peer1.researchers.hf.medchain.global:
    url: grpcs://localhost:11061
    eventUrl: grpcs://localhost:11063
    grpcOptions:
      ssl-target-name-override: peer1.researchers.hf.medchain.global
      grpc.http2.keepalive_time: 15
    tlsCACerts:
      path: "${GOPATH}/src/medchain/medchain-network/fixtures/crypto-config/peerOrganizations/researchers.hf.medchain.global/tlsca/tlsca.researchers.hf.medchain.global-cert.pem"

# Fabric-CA is a special kind of Certificate Authority provided by Hyperledger Fabric which allows certificate management to be done via REST APIs.
certificateAuthorities:
  ca.providers.hf.medchain.global:
    url: https://localhost:7054
    # the properties specified under this object are passed to the 'http' client verbatim when making the request to the Fabric-CA server
    httpOptions:
      verify: false
    registrar:
      enrollId: admin
      enrollSecret: adminpw
    caName: ca.providers.hf.medchain.global

  ca.storages.hf.medchain.global:
    url: https://localhost:7074
    # the properties specified under this object are passed to the 'http' client verbatim when making the request to the Fabric-CA server
    httpOptions:
      verify: false
    registrar:
      enrollId: admin
      enrollSecret: adminpw
    caName: ca.storages.hf.medchain.global
